name: Build M5Stack Projects

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project:
          - name: "test_key_switch_m5stack_basic"
            path: "test_key_switch_m5stack_basic"
            environment: "m5stack-core-esp32"
          - name: "test_key_switch_m5stack_s3"
            path: "test_key_switch_m5stack_s3"
            environment: "m5stack-cores3"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build ${{ matrix.project.name }}
      run: |
        cd ${{ matrix.project.path }}
        pio run -e ${{ matrix.project.environment }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project.name }}-firmware
        path: ${{ matrix.project.path }}/.pio/build/${{ matrix.project.environment }}/firmware.bin
        if-no-files-found: warn
